#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.11.6
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'systemd-udevd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installdeb/13.11.6
dpkg-maintscript-helper rm_conffile /etc/init.d/udev 254.1-4\~ -- "$@"
# End automatically added section
